version: "3"
services:
  mongodb:
    image: mongo:4.0.3
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  springboot:
    image: springboot
    ports:
      - 8080:8080
      - 443:8443
    links:
      - mongodb
   # volumes:
    #  - .:/code  # <--  THIS line enables hot code reloading!